---
title: "LEUK37_Preprocessing"
author: "Aditi Vedi"
date: "2023/11/24"
output: html_document
---

```{r}
library(tidyverse)
library(ggpubr)
library(plater)
library(reshape2)
```

## Read in index data
```{r}
P1 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate1.csv") %>% 
  mutate(Plate = 1, Cell_seeded = "HSC")
P2 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate2.csv") %>% 
  mutate(Plate = 2, Cell_seeded = "HSC")
P3 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate3.csv") %>% 
  mutate(Plate = 3, Cell_seeded = "HSC")
P4 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate4.csv") %>% 
  mutate(Plate = 4, Cell_seeded = "HSC")
P5 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate5.csv") %>% 
  mutate(Plate = 5, Cell_seeded = "HSC")
P6 <- read_csv("Input_data/Index_data/Aditi_Vedi_041120_Specimen_001_Plate6.csv") %>% 
  mutate(Plate = 6, Cell_seeded = "HSC")

Index <- bind_rows(P1, P2, P3, P4, P5, P6) %>% 
  select(-2) %>% 
  unite(Sort_id, Plate, Well)

Index <- Index %>% 
  rename(CD33 = "640 670/30-A", CD45RA = "640 730/45-A", CD34 = "640 780/60-A", 
        CD90 = "561 582/15-A", CD49f = "561 670/14-A", CD38 = "561 780/60-A", 
        CD19 = "488 530/30-A", CD7_10 = "V405 450/50-A", Live_Dead = "V405 525/50-A", CD45 = "V405 780/60-A")

colnames(Index)

Index %>% count(Cell_seeded)

write_csv(Index, "Processed_data/Index_data/LEUK37_Index.csv")
```

```{r}
# Read in collated Index data

Index <- read_csv("Processed_data/Index_data/LEUK37_Index.csv")
```
```{r}

```

## Read in Phenotyping data

```{r}
#Read in plate layout to get sort_id esp for upside down plate

file_path <- "Input_data/Phenotype_data/Harvest_plan_LEUK37_RepliG.csv"

check_plater_format(file_path)

plate <- read_plate(file = file_path, well_ids_column = 'Wells')
plate$Wells <- str_remove(plate$Wells, '(?<=[A-Z])0*(?=[0-9])')

Plate_map <- melt(plate, id = "Wells") %>% 
  filter(!is.na(value)) %>%
  mutate(Plate = as.character(variable), 
         Plate = parse_number(Plate)) %>% 
  unite(Plate_well, Plate, Wells) %>% 
  rename(Sort_id = value) %>% 
  select(-variable)

write_csv(Plate_map, "Processed_data/Phenotype_data/LEUK37_Plate_map.csv")
```

```{r}
Harvested_colonies <- left_join(Plate_map, Index, by = "Sort_id")

Harvested_colonies %>% count(Cell_seeded)
```
```{r}

```

## Read in FACS data
```{r}
FACS <- read_csv("Input_data/Phenotype_data/20231124_LEUK37_AML2_TrueFalse.csv") %>% 
  filter(TrueFalse == "TRUE")
```
```{r}
#Join FACS with sort_id from plate map

True_colonies <- left_join(FACS, Harvested_colonies, by = "Plate_well") %>% 
  filter(TrueFalse == "TRUE")

True_colonies %>% count(Cell_seeded)

write_csv(True_colonies, "Processed_data/Phenotype_data/LEUK37_True_colonies.csv")
```
```{r}

```

## Read in current seq VAF data

```{r}
Sample_id <- read_csv("Input_data/Genotype_data/MiniseqR56_sample_info.csv") %>% 
  select(1,3,5:6) %>% 
  mutate(Sample_id = parse_number(`sample name`)) %>% 
  filter(Exp == "LEUK37") %>% 
  select(2,3,5)
Sample_id$Plate_well <- str_remove(Sample_id$Plate_well, '(?<=[A-Z])0*(?=[0-9])')
```
### Run statistics
```{r}
Run <- read_csv("Input_data/Genotype_data/run_statistics.csv")
```

```{r}
# Keeping only samples from our run

Run<- Run %>% 
  separate(...1, into = c("Sample_id", NA, NA)) %>% 
  filter(str_detect(Sample_id, "sample")) %>% 
  mutate(Sample_id = parse_number(Sample_id)) %>% 
  distinct(Sample_id, .keep_all = TRUE) %>% 
  select(Sample_id, `2:25456597-25457770`) %>% 
  rename(Depth = `2:25456597-25457770`)
```
### mutect
```{r}
mutect <- read_csv("Input_data/Genotype_data/total_mutect.csv") %>% 
  mutate(Start = as.numeric(Start))
```
```{r}
# Keeping only samples from our run
# looking at DNMT3A R882H (Start/End position 25457242 as per Human assembly: Feb 2009(GRCh7/hg19))

mutect <- mutect %>% 
  filter(Start == 25457242, str_detect(sample_name, "sample")) %>% 
  distinct(sample_name, .keep_all = TRUE) %>% 
  select(sample_name, VAF) %>% 
  rename(VAF.mutect = VAF, Sample_id = sample_name) %>% 
  separate(Sample_id, into = c("Sample_id", NA, NA)) %>% 
  mutate(Sample_id = parse_number(Sample_id))
```
### varscan
```{r}
varscan <- read_csv("Input_data/Genotype_data/total_varscan.csv") %>% 
  mutate(Start = as.numeric(Start))
```
```{r}
# Keeping only samples from our run
# looking at DNMT3A R882H (Start/End position 25457242 as per Human assembly: Feb 2009(GRCh7/hg19))

varscan <- varscan %>% 
  filter(Start == 25457242, str_detect(sample_name, "sample")) %>% 
  distinct(sample_name, .keep_all = TRUE) %>% 
  select(sample_name, VAF) %>% 
  rename(VAF.varscan = VAF, Sample_id = sample_name) %>% 
  separate(Sample_id, into = c("Sample_id", NA, NA)) %>% 
  mutate(Sample_id = parse_number(Sample_id))
```
### platypus
```{r}
platypus <- read_csv("Input_data/Genotype_data/total_platypus.csv") %>% 
  mutate(Start = as.numeric(Start))
```
```{r}
# Keeping only samples from our run
# looking at DNMT3A R882H (Start/End position 25457242 as per Human assembly: Feb 2009(GRCh7/hg19))

platypus <- platypus %>% 
  filter(Start == 25457242, str_detect(sample_name, "sample")) %>% 
  distinct(sample_name, .keep_all = TRUE) %>% 
  select(sample_name, VAF) %>% 
  rename(VAF.platypus = VAF, Sample_id = sample_name) %>% 
  separate(Sample_id, into = c("Sample_id", NA, NA)) %>% 
  mutate(Sample_id = parse_number(Sample_id))
```
```{r}

```

```{r}
# Combine all above data into single file containing depth from run stats and VAF from 3 variant callers

VAF <- left_join(Run, varscan, by = "Sample_id")
VAF <- left_join(VAF, mutect, by = "Sample_id")
VAF <- left_join(VAF, platypus, by = "Sample_id")
```

```{r}
VAF <- VAF %>% 
  arrange(Depth)
```
```{r}
# filter out the colonies with low depth. i.e. keep colonies above the lowest depth that has at least 2 variant callers that call a colony mutant

Temp_VAF <- VAF[ rowSums(VAF[c('VAF.varscan',	'VAF.mutect',	'VAF.platypus')] > 0.02 , na.rm=TRUE ) >= 2,]
Depth_cutoff <- min(Temp_VAF$Depth)

VAF <- VAF %>% 
  filter(Depth>=Depth_cutoff)
```
```{r}
# Calculate mean VAF based on the 3 variant callers

VAF <- VAF %>% 
    rowwise() %>%
  mutate(mean_VAF = mean(c(VAF.varscan, VAF.mutect, VAF.platypus), na.rm = TRUE)) %>%
  ungroup()
```

```{r}
# If any of the VAFs' mean has been returned as NA (i.e. all variant callers were NA) then give it VAF = 0 ie WT
VAF$mean_VAF[is.nan(VAF$mean_VAF)]<-0
```
```{r}

```

### Assign Mut/WT to VAFs
```{r}
VAF <- VAF %>% 
  mutate (DNMT3A = case_when(mean_VAF < 0.02 ~ "WT",
                                 mean_VAF >= 0.02 ~ "MUT"),
          DNMT3A = fct_relevel(DNMT3A, c("WT", "MUT")))

VAF <- left_join(Sample_id, VAF, by = "Sample_id")

VAF %>% count(DNMT3A)

write_csv(VAF, "Processed_data/Genotype_data/LEUK37_final_VAF.csv")
```
```{r}

```

## Join VAF with True colonies
```{r}
Final_data <- left_join(VAF, True_colonies, by = "Sort_id") %>% 
  filter(!is.na(fcs.name))

Final_data %>% count(DNMT3A)
```



```{r}
dim(Final_data)
```

```{r}

```

```{r}
# clean up and save final data

names(Final_data)[names(Final_data) == 'Plate_well.x'] <- 'Plate_well'

drop = c('Plate_well.y')

Final_data <- Final_data[,!(names(Final_data) %in% drop)]

dim(Final_data)
```

```{r}

```

```{r}
filename_prefix <- format(as.Date(Sys.time()), "%Y%m%d")

outname <- paste0("Processed_data/",filename_prefix,"_LEUK37_Final_data.csv")

write_csv( Final_data,  outname)

print(outname)
```

```{r}

```

```{r}
sessionInfo()
```



